"""add unique to image name

Revision ID: 52b9d4504a65
Revises: 4d21b1b0f454
Create Date: 2023-08-17 11:41:42.286102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b9d4504a65'
down_revision: Union[str, None] = '4d21b1b0f454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
